server:
    port: ${POST}
    
spring:
    application:
            name: homestay

    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: ${DRIVER_CLASS_NAME}

        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            poolName: Hikari
            auto-commit: false
            maximum-pool-size: 10         
            minimum-idle: 2                
            idle-timeout: 30000             # Thời gian (ms) tối đa một kết nối nhàn rỗi được giữ trước khi bị loại bỏ (30 giây)
            connection-timeout: 10000       # Thời gian chờ tối đa (ms) để lấy được connection từ pool (30 giây)
            max-lifetime: 1800000           # Thời gian tối đa (ms) mà một connection có thể tồn tại trong pool (30 phút)
            data-source-properties:
                cachePrepStmts: true        # Cho phép tái sử dụng câu lệnh SQL (lưu trong cache)
                prepStmtCacheSize: 250      # Số lượng SQL tối đa được lưu trữ
                prepStmtCacheSqlLimit: 2048 # Giới hạn dộ dài SQL

    jpa:
        hibernate:
            ddl-auto: update
        # show-sql: true


    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MY_EMAIL}
        password: ${MY_EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    
    # config pagination start 1, not 0
    data:
        web:
            pageable:
                one-indexed-parameters: true
    # config pagination end

springdoc:
    swagger-ui:
        path: /swagger-ui.html
        url: /v3/api-docs   #BẮT BUỘC: yêu cầu Swagger UI load đúng file JSON thật
    api-docs:
        enabled: true

payment:
    vnpay:
        tmn-code: ${TMN-CODE}   
        secret-key: ${VNPAY_SECRET_KEY}
        vnp_PayUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
        vnp_ReturnUrl: http://localhost:3000/payments/payment-callback
        timeout: 15 # in minutes
        

cloudinary:
    cloud_name: ${YOUR_CLOUD_NAME}
    api_key: ${YOUR_API_KEY}
    api_secret: ${YOUR_API_SECRET}


security:
    authentication:
        jwt:
            # This token must be encoded using Base64 and be at least 256 bits long 
            # (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
            base64-secret: ${BASE64-SECRET}
            access-token-validity-in-seconds: ${ACCESS-TOKEN-VALIDITY-IN-SECONDS}
            refresh-token-validity-in-seconds: ${REFRESH-TOKEN-VALIDITY-IN-SECONDS}

# base path
quangkhongbiet:
    upload-file:
        base-uri: file:///D:/github-tutorio-demo/upload_homestay_img/
    firebase:
        config-path: D:/github-tutorio-demo/serviceAccountKey.json


logging:
    level:
        org:
            springframework:
                web:
                    client: DEBUG
        # com:
        #     zaxxer:
        #         hikari: DEBUG

        vn:
            quangkhongbiet:
                "[homestay_booking]": DEBUG

