server:
    port: 8080
    
spring:
    jpa:
        hibernate:
            ddl-auto: update
        # show-sql: true
    datasource:
        url: jdbc:postgresql://localhost:5432/booking_homestay
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
    application:
        name: homestay
    # config pagination start 1, not 0
    data:
        web:
            pageable:
                one-indexed-parameters: true
    # config pagination end

logging:
    level:
        org:
            springframework:
                web:
                    client: DEBUG
# cloudinary
cloudinary:
    cloud_name: ${YOUR_CLOUD_NAME}
    api_key: ${YOUR_API_KEY}
    api_secret: ${YOUR_API_SECRET}

security:
    authentication:
        jwt:
            # This token must be encoded using Base64 and be at least 256 bits long 
            # (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
            base64-secret: ${BASE64-SECRET}
            access-token-validity-in-seconds: ${ACCESS-TOKEN-VALIDITY-IN-SECONDS}
            refresh-token-validity-in-seconds: ${REFRESH-TOKEN-VALIDITY-IN-SECONDS}
