server:
    port: 8080
    
spring:
    jpa:
        hibernate:
            ddl-auto: update
        # show-sql: true
    datasource:
        url: jdbc:postgresql://localhost:5432/booking_homestay
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver
    application:
        name: homestay
    # config pagination start 1, not 0
    data:
        web:
            pageable:
                one-indexed-parameters: true
    # config pagination end

logging:
    level:
        org:
            springframework:
                web:
                    client: DEBUG
